<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>async</title>
</head>
<body>
  <script>
    // async函数返回的 Promise 对象，必须等到内部所有await命令后面的 Promise 对象执行完，才会发生状态改变，除非遇到return语句或者抛出错误
    let promise1 = async function(){
      console.log(1)
    }
    let promise2 = async function(){
      console.log(2)
    }
    let promise3 = async function(){
      console.log(3)
    }

    let async1 = async function(){
      await promise1()
      await promise2()
      await promise3()
    }

    async1().then(()=>{
      console.log('async1')
    })


    // 正常情况下，await命令后面是一个 Promise 对象，返回该对象的结果。如果不是 Promise 对象，就直接返回对应的值。

    async function async2(){
      // 等同于return123
      return await 123
    }

    async2().then(v=>console.log(v))


    // await命令后面的 Promise 对象如果变为reject状态，则reject的参数会被catch方法的回调函数接收到。
    async function async3() {
      await Promise.reject('出错了');
      await Promise.resolve('hello world');       // 不会执行
    }

    async3().then(v => console.log(v)).catch(e => console.log(e))
    // 出错了


    // 放在try catch结构里面的话，不管异步操作是否成功，第二个await都会执行
    async function async4(){
      try {
        await Promise.reject('出错了');
      } catch(e) {
      }
      return await Promise.resolve('hello world');
    }
    async4()

    // 注意点
    // 1，await命令后面的Promise对象，运行结果可能是rejected，所以最好把await命令放在try...catch代码块中。
    async function myFun(){
      try{
        await async4()
      }catch(err){
        console.log(err);
      }
    }

    // 另外一种写法
    async function myFunC(){
      await async4().catch(err=>console.log(err))
    }

    // 2.多个await命令后面的异步操作，如果不存在继发关系，最好让它们同时触发。
    async function async5(){
      // 等同于return123
      return Promise.resolve(456)
    }

    // 写法一
    async function async6(){
      let [foo1,bar1] = await Promise.all([async2(),async5()]);
      console.log('foo1',foo1);
      console.log('bar1',bar1);
    }
    async6()
    // 写法二

    async function async7(){
      let fooPromise  = async2()
      let barPromise  = async5()
      let foo = await fooPromise;
      let bar = await barPromise;
    }
    
    // 并发处理.Promise.all   / 或者for of
    async function dbFun(){
      let docs = [1,2,4];
      let promiseData = docs.map((doc,index)=>new Promise((resolve,reject)=>{
        setTimeout(()=>{
          console.log(doc);
          resolve(doc)
        },500)
      }));
      let results = await Promise.all(promiseData);
      console.log(results)
    }
    dbFun()

    // 或者使用下面的写法
    async function dbFun1(){
      let docs = [1,2,4];
      let promiseData = docs.map((doc,index)=>new Promise((resolve,reject)=>{
        setTimeout(()=>{
          console.log(doc);
          resolve(doc)
        },500)
      }));
      let results = [];
      for(let promise of promiseData){
        results.push(await promise)
      }
      console.log(results)
    }
    dbFun1()

    const promise4 = ()=>{
      return new Promise((resolve,reject)=>{
        setTimeout(()=>{
          reject(123)
        },5000)
      })
    };
    
    // async 函数可以保留运行堆栈
    const one = ()=>{
      var a = 2;
      promise4().then(()=>c()).catch(e=>{
        console.log(a)
        console.log('错误信息',e)
      })
      console.log('a',a)
    }
    one()
  </script>
</body>
</html>